# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from darknet_ros_msgs/BoundingBoxes_tensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import darknet_ros_msgs.msg

class BoundingBoxes_tensor(genpy.Message):
  _md5sum = "28b99bb7e3f0d3196525501e81626006"
  _type = "darknet_ros_msgs/BoundingBoxes_tensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """BoundingBox_tensor[] boundingboxes_tensor

================================================================================
MSG: darknet_ros_msgs/BoundingBox_tensor
float64 probability
int64 top
int64 left
int64 width
int64 height
int16 id
string Class
"""
  __slots__ = ['boundingboxes_tensor']
  _slot_types = ['darknet_ros_msgs/BoundingBox_tensor[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       boundingboxes_tensor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoundingBoxes_tensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.boundingboxes_tensor is None:
        self.boundingboxes_tensor = []
    else:
      self.boundingboxes_tensor = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.boundingboxes_tensor)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundingboxes_tensor:
        _x = val1
        buff.write(_get_struct_d4qh().pack(_x.probability, _x.top, _x.left, _x.width, _x.height, _x.id))
        _x = val1.Class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.boundingboxes_tensor is None:
        self.boundingboxes_tensor = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundingboxes_tensor = []
      for i in range(0, length):
        val1 = darknet_ros_msgs.msg.BoundingBox_tensor()
        _x = val1
        start = end
        end += 42
        (_x.probability, _x.top, _x.left, _x.width, _x.height, _x.id,) = _get_struct_d4qh().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Class = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Class = str[start:end]
        self.boundingboxes_tensor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.boundingboxes_tensor)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundingboxes_tensor:
        _x = val1
        buff.write(_get_struct_d4qh().pack(_x.probability, _x.top, _x.left, _x.width, _x.height, _x.id))
        _x = val1.Class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.boundingboxes_tensor is None:
        self.boundingboxes_tensor = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundingboxes_tensor = []
      for i in range(0, length):
        val1 = darknet_ros_msgs.msg.BoundingBox_tensor()
        _x = val1
        start = end
        end += 42
        (_x.probability, _x.top, _x.left, _x.width, _x.height, _x.id,) = _get_struct_d4qh().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Class = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Class = str[start:end]
        self.boundingboxes_tensor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d4qh = None
def _get_struct_d4qh():
    global _struct_d4qh
    if _struct_d4qh is None:
        _struct_d4qh = struct.Struct("<d4qh")
    return _struct_d4qh
